services:
  writebook:
    image: marcogll/writebook_s23:latest
    volumes:
      - writebook_storage:/rails/storage
    env_file:
      - .env
    restart: unless-stopped

volumes:
  writebook_storage:
